export const ROLE_PERMISSIONS = {
  CITIZEN: ['CREATE_REQUEST', 'VIEW_REQUEST'],
  INSITUTIONS: ['CREATE_REQUEST', 'VIEW_REQUEST'],
  FACTORY: ['VIEW_REQUEST'],
  EXTERNAL_PARTNER: ['VIEW_REQUEST'],
  COLLECTOR: ['VIEW_REQUEST', 'APPROVE_REQUEST'],

  ADMIN: ['*'], 
};


