import { MigrationInterface, QueryRunner } from "typeorm";

export class WasteMigration1777831829938 implements MigrationInterface {
    name = 'WasteMigration1777831829938'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP CONSTRAINT "FK_2c398e56c9ef0a30554887187eb"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "FK_de1571d451cb38df5bcdc3923b8"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP CONSTRAINT "FK_b9054dabcda324ab88fe5869da0"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP CONSTRAINT "FK_943501abc7ca3f47bf6b5ba4b27"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP CONSTRAINT "FK_c8fcfa57ed4363919e5db5e3d39"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "FK_a7d260d23da33780abd8a4cbf3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e8604b1bbe14e551469670e3e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98480b28ff3a2c27d19c776a72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_956ef814aee254185e0ee0dfe2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c42789554ebc81569ca9f6efcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7954869e79dc5cfbc322d2742d"`);
        await queryRunner.query(`CREATE TABLE "factory_waste_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "other_text" character varying, "factory_id" uuid, "waste_category_id" uuid, CONSTRAINT "PK_1f43b92e054238e646f6580ec86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "desscript_location" character varying, "coordinates" geography(Point,4326), "address" character varying NOT NULL, "province_id" uuid, "cititzen_profile_id" uuid, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "External_Partner_waste_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "other_text" character varying, "External_partner_id" uuid, "waste_category_id" uuid, CONSTRAINT "PK_f79306efc78586ea0f524a5d35a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "institution_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "other_text" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0c8b7a289e9fefcaf6d46a2d1c1" UNIQUE ("name"), CONSTRAINT "PK_107759c27486a58ae2a5e1cd6aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "institution_waste_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "other_text" character varying, "institution_id" uuid, "waste_category_id" uuid, CONSTRAINT "PK_ae061a034a2848276a3ac87a83a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "waste_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9783f736537a21a16afce9a2133" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" character varying NOT NULL, "completed_steps" json NOT NULL DEFAULT '[]', "accountId" uuid, CONSTRAINT "PK_df158a7777b4f38c6a60e1a0339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c9955930ac51f459d30161f53" ON "account_progress" ("accountId") `);
        await queryRunner.query(`CREATE TYPE "public"."media_file_type_enum" AS ENUM('INDUSTRIAL_REG', 'LICENSE', 'ID_CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."media_owner_type_enum" AS ENUM('COLLECTOR', 'INSITUTIONS', 'FACTORY')`);
        await queryRunner.query(`CREATE TYPE "public"."media_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "file_type" "public"."media_file_type_enum" NOT NULL, "owner_id" character varying NOT NULL, "owner_type" "public"."media_owner_type_enum" NOT NULL, "status" "public"."media_status_enum" NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "birth_date"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "profile_add_profile_data"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "profile_add_location"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "driving_cretificate_photo"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "profile_add_profile_data"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "profile_add_location"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "factory_manager"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_d12db2d224ebe031b4f64a02805"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "commercial_register"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_523c191dc31203c6cc3556cfa53"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "factory_register"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "coordinates"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "province_id"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "profile_add_profile_data"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "profile_add_location"`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "profile_add_profile_data"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "profile_add_location"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "external_partner_manager"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP CONSTRAINT "UQ_30236f84619307fdc1e2849b896"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "commercial_register"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "profile_add_profile_data"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "profile_add_location"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "institution_manager"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_216f5213567bf686020e6b9c49c"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "commercial_registration_number"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "desscript_location" character varying`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "national_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD CONSTRAINT "UQ_569251689ea031e0695056b8b26" UNIQUE ("national_id")`);
        await queryRunner.query(`CREATE TYPE "public"."collector_profiles_shift_enum" AS ENUM('MORNING', 'EVENING')`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "shift" "public"."collector_profiles_shift_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "desscript_location" character varying`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "factory_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "commercial_record" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_3be80d063c46023251f937ea007" UNIQUE ("commercial_record")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "industrial_record" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_0b14824a2e8161e50dd7ce1e04d" UNIQUE ("industrial_record")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "tax_number" character varying`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "factory_slogo" character varying`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "average_order_quantity" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."factory_profiles_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "estimation_order_schedule" "public"."factory_profiles_estimation_order_schedule_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "delivery_preference" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."factory_profiles_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "perferred_delivery_schedule" "public"."factory_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "desscript_location" character varying`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "external_partner_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "external_partner_slogo" character varying`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "average_order_quantity" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_profiles_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "estimation_order_schedule" "public"."external_partner_profiles_estimation_order_schedule_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "delivery_preference" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_profiles_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "perferred_delivery_schedule" "public"."external_partner_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "desscript_location" character varying`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "institution_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "license_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_e5027f0059db653aa8eb50dfd45" UNIQUE ("license_number")`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "tax_number" character varying`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "institution_slogo" character varying`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "estimated_waste_quantity" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."institution_profiles_collection_frequney_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "collection_frequney" "public"."institution_profiles_collection_frequney_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "preferred_collection_time" text array NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "institutionType" uuid`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_8952a4248803f54fafc3d3a2285" UNIQUE ("institutionType")`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ALTER COLUMN "coordinates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ALTER COLUMN "coordinates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ALTER COLUMN "coordinates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ALTER COLUMN "coordinates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ALTER COLUMN "address" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD CONSTRAINT "FK_bb199ed4b85bb86e2e8ff0d4ca6" FOREIGN KEY ("factory_id") REFERENCES "factory_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD CONSTRAINT "FK_c4387de766f5e1c1138ae1341dc" FOREIGN KEY ("waste_category_id") REFERENCES "waste_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_b02683eefd239a9fd4883721d4b" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_c66164f418fb3b14d628e14caf3" FOREIGN KEY ("cititzen_profile_id") REFERENCES "citizen_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD CONSTRAINT "FK_5c9b1064a18fa7a24531b992eb1" FOREIGN KEY ("External_partner_id") REFERENCES "external_partner_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD CONSTRAINT "FK_45c6748ec2496b1ee5c7e093c78" FOREIGN KEY ("waste_category_id") REFERENCES "waste_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "FK_8952a4248803f54fafc3d3a2285" FOREIGN KEY ("institutionType") REFERENCES "institution_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD CONSTRAINT "FK_4b0b872dc809bb10fccfbf11faa" FOREIGN KEY ("institution_id") REFERENCES "institution_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD CONSTRAINT "FK_72d12948d26a778020641e2ab52" FOREIGN KEY ("waste_category_id") REFERENCES "waste_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_progress" ADD CONSTRAINT "FK_6c9955930ac51f459d30161f536" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "account_progress" DROP CONSTRAINT "FK_6c9955930ac51f459d30161f536"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP CONSTRAINT "FK_72d12948d26a778020641e2ab52"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP CONSTRAINT "FK_4b0b872dc809bb10fccfbf11faa"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "FK_8952a4248803f54fafc3d3a2285"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP CONSTRAINT "FK_45c6748ec2496b1ee5c7e093c78"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP CONSTRAINT "FK_5c9b1064a18fa7a24531b992eb1"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_c66164f418fb3b14d628e14caf3"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_b02683eefd239a9fd4883721d4b"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP CONSTRAINT "FK_c4387de766f5e1c1138ae1341dc"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP CONSTRAINT "FK_bb199ed4b85bb86e2e8ff0d4ca6"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ALTER COLUMN "coordinates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ALTER COLUMN "coordinates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ALTER COLUMN "coordinates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ALTER COLUMN "address" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ALTER COLUMN "coordinates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_8952a4248803f54fafc3d3a2285"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "institutionType"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "preferred_collection_time"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "collection_frequney"`);
        await queryRunner.query(`DROP TYPE "public"."institution_profiles_collection_frequney_enum"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "estimated_waste_quantity"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "institution_slogo"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "tax_number"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_e5027f0059db653aa8eb50dfd45"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "license_number"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "institution_name"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "desscript_location"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "perferred_delivery_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "delivery_preference"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "estimation_order_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "average_order_quantity"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "external_partner_slogo"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "external_partner_name"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "desscript_location"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "perferred_delivery_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."factory_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "delivery_preference"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "estimation_order_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."factory_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "average_order_quantity"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "factory_slogo"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "tax_number"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_0b14824a2e8161e50dd7ce1e04d"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "industrial_record"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_3be80d063c46023251f937ea007"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "commercial_record"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "factory_name"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "desscript_location"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "shift"`);
        await queryRunner.query(`DROP TYPE "public"."collector_profiles_shift_enum"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP CONSTRAINT "UQ_569251689ea031e0695056b8b26"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "national_id"`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" DROP COLUMN "desscript_location"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "commercial_registration_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_216f5213567bf686020e6b9c49c" UNIQUE ("commercial_registration_number")`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "institution_manager" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "profile_add_location" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "profile_add_profile_data" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "commercial_register" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD CONSTRAINT "UQ_30236f84619307fdc1e2849b896" UNIQUE ("commercial_register")`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "external_partner_manager" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "profile_add_location" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "profile_add_profile_data" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "profile_add_location" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "profile_add_profile_data" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "province_id" uuid`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD "coordinates" geography(Point,4326)`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "factory_register" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_523c191dc31203c6cc3556cfa53" UNIQUE ("factory_register")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "commercial_register" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_d12db2d224ebe031b4f64a02805" UNIQUE ("commercial_register")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "factory_manager" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "profile_add_location" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "profile_add_profile_data" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "driving_cretificate_photo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "profile_add_location" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "profile_add_profile_data" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD "birth_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TYPE "public"."media_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_owner_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."media_file_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c9955930ac51f459d30161f53"`);
        await queryRunner.query(`DROP TABLE "account_progress"`);
        await queryRunner.query(`DROP TABLE "waste_categories"`);
        await queryRunner.query(`DROP TABLE "institution_waste_category"`);
        await queryRunner.query(`DROP TABLE "institution_types"`);
        await queryRunner.query(`DROP TABLE "External_Partner_waste_category"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "factory_waste_category"`);
        await queryRunner.query(`CREATE INDEX "IDX_7954869e79dc5cfbc322d2742d" ON "institution_profiles" USING GiST ("coordinates") `);
        await queryRunner.query(`CREATE INDEX "IDX_c42789554ebc81569ca9f6efcb" ON "external_partner_profiles" USING GiST ("coordinates") `);
        await queryRunner.query(`CREATE INDEX "IDX_956ef814aee254185e0ee0dfe2" ON "citizen_profiles" USING GiST ("coordinates") `);
        await queryRunner.query(`CREATE INDEX "IDX_98480b28ff3a2c27d19c776a72" ON "factory_profiles" USING GiST ("coordinates") `);
        await queryRunner.query(`CREATE INDEX "IDX_e8604b1bbe14e551469670e3e5" ON "collector_profiles" USING GiST ("coordinates") `);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "FK_a7d260d23da33780abd8a4cbf3e" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD CONSTRAINT "FK_c8fcfa57ed4363919e5db5e3d39" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD CONSTRAINT "FK_943501abc7ca3f47bf6b5ba4b27" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citizen_profiles" ADD CONSTRAINT "FK_b9054dabcda324ab88fe5869da0" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "FK_de1571d451cb38df5bcdc3923b8" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collector_profiles" ADD CONSTRAINT "FK_2c398e56c9ef0a30554887187eb" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
