import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatedMigration1778277117945 implements MigrationInterface {
    name = 'UpdatedMigration1778277117945'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP CONSTRAINT "FK_bb199ed4b85bb86e2e8ff0d4ca6"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP CONSTRAINT "FK_5c9b1064a18fa7a24531b992eb1"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP CONSTRAINT "FK_4b0b872dc809bb10fccfbf11faa"`);
        await queryRunner.query(`CREATE TYPE "public"."factory_materials_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TYPE "public"."factory_materials_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`CREATE TABLE "factory_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "average_order_quantity" character varying NOT NULL, "estimation_order_schedule" "public"."factory_materials_estimation_order_schedule_enum" NOT NULL, "delivery_preference" boolean NOT NULL DEFAULT false, "perferred_delivery_schedule" "public"."factory_materials_perferred_delivery_schedule_enum", "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "factory_profile_id" uuid, CONSTRAINT "REL_1644369a44659c53c079ec651d" UNIQUE ("factory_profile_id"), CONSTRAINT "PK_518db13b0182e309fc6056ed985" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_materials_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_materials_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`CREATE TABLE "external_partner_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "average_order_quantity" character varying NOT NULL, "estimation_order_schedule" "public"."external_partner_materials_estimation_order_schedule_enum" NOT NULL, "delivery_preference" boolean NOT NULL DEFAULT false, "perferred_delivery_schedule" "public"."external_partner_materials_perferred_delivery_schedule_enum", "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "external_partner_profile_id" uuid, CONSTRAINT "REL_bb90a11f456c25986d90486c0d" UNIQUE ("external_partner_profile_id"), CONSTRAINT "PK_76035f09a6389947cf5bfa80261" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."institution_materials_collection_frequney_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "institution_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estimated_waste_quantity" character varying NOT NULL, "collection_frequney" "public"."institution_materials_collection_frequney_enum" NOT NULL, "preferred_collection_time" text array NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "institution_profile_id" uuid, CONSTRAINT "REL_743e7641c805fe9a84cc73a065" UNIQUE ("institution_profile_id"), CONSTRAINT "PK_237ee3edc261f4f56a28e9156f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP COLUMN "factory_id"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP COLUMN "other_text"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "estimation_order_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."factory_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "delivery_preference"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "perferred_delivery_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."factory_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "average_order_quantity"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP COLUMN "External_partner_id"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP COLUMN "other_text"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "estimation_order_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "delivery_preference"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "perferred_delivery_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "average_order_quantity"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "collection_frequney"`);
        await queryRunner.query(`DROP TYPE "public"."institution_profiles_collection_frequney_enum"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "estimated_waste_quantity"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "preferred_collection_time"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP COLUMN "institution_id"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP COLUMN "other_text"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD "material_id" uuid`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "material_id" uuid`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_5faeee215a46313ba91789d884b" UNIQUE ("material_id")`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD "material_id" uuid`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "material_id" uuid`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD CONSTRAINT "UQ_3f07657c40fdb73ce3add067de2" UNIQUE ("material_id")`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "material_id" uuid`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_707c6b19ca23eeb47fcd303720d" UNIQUE ("material_id")`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD "material_inputs_id" uuid`);
        await queryRunner.query(`ALTER TABLE "media" ADD "public_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_2b06fb3379c78a0c634315d5f79" UNIQUE ("factory_phone")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_3be80d063c46023251f937ea007" UNIQUE ("commercial_record")`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "UQ_0b14824a2e8161e50dd7ce1e04d" UNIQUE ("industrial_record")`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "coordinates" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD CONSTRAINT "UQ_e5adef643f12d18aac9490ecb0b" UNIQUE ("external_partner_phone")`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_b93c6f4420b2f525530c448722d" UNIQUE ("institution_phone")`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "UQ_e5027f0059db653aa8eb50dfd45" UNIQUE ("license_number")`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD CONSTRAINT "FK_196eedb59ca5e5f8f392e3c5e44" FOREIGN KEY ("material_id") REFERENCES "factory_materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory_materials" ADD CONSTRAINT "FK_1644369a44659c53c079ec651d3" FOREIGN KEY ("factory_profile_id") REFERENCES "factory_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD CONSTRAINT "FK_5faeee215a46313ba91789d884b" FOREIGN KEY ("material_id") REFERENCES "factory_materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD CONSTRAINT "FK_89fbc93f7b8a999e4cc27db8d4d" FOREIGN KEY ("material_id") REFERENCES "external_partner_materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_partner_materials" ADD CONSTRAINT "FK_bb90a11f456c25986d90486c0d9" FOREIGN KEY ("external_partner_profile_id") REFERENCES "external_partner_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD CONSTRAINT "FK_3f07657c40fdb73ce3add067de2" FOREIGN KEY ("material_id") REFERENCES "external_partner_materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD CONSTRAINT "FK_707c6b19ca23eeb47fcd303720d" FOREIGN KEY ("material_id") REFERENCES "institution_materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_materials" ADD CONSTRAINT "FK_743e7641c805fe9a84cc73a0659" FOREIGN KEY ("institution_profile_id") REFERENCES "institution_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD CONSTRAINT "FK_18b917b85b442b70f8563bb32ad" FOREIGN KEY ("material_inputs_id") REFERENCES "institution_materials"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP CONSTRAINT "FK_18b917b85b442b70f8563bb32ad"`);
        await queryRunner.query(`ALTER TABLE "institution_materials" DROP CONSTRAINT "FK_743e7641c805fe9a84cc73a0659"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "FK_707c6b19ca23eeb47fcd303720d"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP CONSTRAINT "FK_3f07657c40fdb73ce3add067de2"`);
        await queryRunner.query(`ALTER TABLE "external_partner_materials" DROP CONSTRAINT "FK_bb90a11f456c25986d90486c0d9"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP CONSTRAINT "FK_89fbc93f7b8a999e4cc27db8d4d"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "FK_5faeee215a46313ba91789d884b"`);
        await queryRunner.query(`ALTER TABLE "factory_materials" DROP CONSTRAINT "FK_1644369a44659c53c079ec651d3"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP CONSTRAINT "FK_196eedb59ca5e5f8f392e3c5e44"`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "media" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_e5027f0059db653aa8eb50dfd45"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_b93c6f4420b2f525530c448722d"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP CONSTRAINT "UQ_e5adef643f12d18aac9490ecb0b"`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "coordinates" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_0b14824a2e8161e50dd7ce1e04d"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_3be80d063c46023251f937ea007"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_2b06fb3379c78a0c634315d5f79"`);
        await queryRunner.query(`ALTER TABLE "media" DROP COLUMN "public_id"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" DROP COLUMN "material_inputs_id"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP CONSTRAINT "UQ_707c6b19ca23eeb47fcd303720d"`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP CONSTRAINT "UQ_3f07657c40fdb73ce3add067de2"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP CONSTRAINT "UQ_5faeee215a46313ba91789d884b"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" DROP COLUMN "material_id"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD "other_text" character varying`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD "institution_id" uuid`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "preferred_collection_time" text array`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "estimated_waste_quantity" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."institution_profiles_collection_frequney_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "institution_profiles" ADD "collection_frequney" "public"."institution_profiles_collection_frequney_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "average_order_quantity" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_profiles_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "perferred_delivery_schedule" "public"."external_partner_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "delivery_preference" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."external_partner_profiles_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "external_partner_profiles" ADD "estimation_order_schedule" "public"."external_partner_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD "other_text" character varying`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD "External_partner_id" uuid`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "average_order_quantity" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."factory_profiles_perferred_delivery_schedule_enum" AS ENUM('MORNING', 'AFTERNOON', 'EVENING', 'FLEXIBLE')`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "perferred_delivery_schedule" "public"."factory_profiles_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "delivery_preference" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."factory_profiles_estimation_order_schedule_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY')`);
        await queryRunner.query(`ALTER TABLE "factory_profiles" ADD "estimation_order_schedule" "public"."factory_profiles_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD "other_text" character varying`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD "factory_id" uuid`);
        await queryRunner.query(`DROP TABLE "institution_materials"`);
        await queryRunner.query(`DROP TYPE "public"."institution_materials_collection_frequney_enum"`);
        await queryRunner.query(`DROP TABLE "external_partner_materials"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_materials_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."external_partner_materials_estimation_order_schedule_enum"`);
        await queryRunner.query(`DROP TABLE "factory_materials"`);
        await queryRunner.query(`DROP TYPE "public"."factory_materials_perferred_delivery_schedule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."factory_materials_estimation_order_schedule_enum"`);
        await queryRunner.query(`ALTER TABLE "institution_waste_category" ADD CONSTRAINT "FK_4b0b872dc809bb10fccfbf11faa" FOREIGN KEY ("institution_id") REFERENCES "institution_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "External_Partner_waste_category" ADD CONSTRAINT "FK_5c9b1064a18fa7a24531b992eb1" FOREIGN KEY ("External_partner_id") REFERENCES "external_partner_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory_waste_category" ADD CONSTRAINT "FK_bb199ed4b85bb86e2e8ff0d4ca6" FOREIGN KEY ("factory_id") REFERENCES "factory_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
