import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  OneToMany,
  Index,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { CollectorProfile } from '@src/user/entities/profile/collector-profile.entity';
import { CollectionRequest } from './collection-request.entity';
import { CollectionRouteStatus } from '../enums/collection-route-status.enum';

/**
 * A driver's tour: the requests assigned to him, ordered by their
 * `route_sequence`. There is no separate stops table — the request is the
 * stop — so the driver's day is simply "my route, ordered, all of it".
 *
 * PLANNED routes still accept merges; IN_PROGRESS ones do not. A route is
 * cancelled only when every request on it can be released (or handed back to
 * the queue) by the shift-handover logic.
 */
@Entity('collection_routes')
@Index(['driverId'])
@Index(['status'])
export class CollectionRoute {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** RTE-YYYYMMDD-### — generated by the service, never edited. */
  @Column({ name: 'route_number', length: 32, unique: true })
  routeNumber: string;

  @ManyToOne(() => CollectorProfile, { nullable: false, onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'driver_id' })
  driver: CollectorProfile;

  @Column({ name: 'driver_id' })
  driverId: string;

  @Column({
    type: 'enum',
    enum: CollectionRouteStatus,
    enumName: 'collection_route_status',
    default: CollectionRouteStatus.PLANNED,
  })
  status: CollectionRouteStatus;

  @Column({ name: 'started_at', type: 'timestamptz', nullable: true })
  startedAt?: Date | null;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt?: Date | null;

  @Column({ name: 'cancelled_at', type: 'timestamptz', nullable: true })
  cancelledAt?: Date | null;

  @OneToMany(() => CollectionRequest, (request) => request.route)
  requests: CollectionRequest[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
