import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  OneToMany,
  Index,
  Unique,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Account } from '@src/user/entities/account.entity';
import { CollectionRoute } from './collection-route.entity';
import { CollectionPlan } from './collection-plan.entity';
import { CollectionRequestLine } from './collection-request-line.entity';
import { CollectionRequestAssignment } from './collection-request-assignment.entity';
import {
  CollectionRequestStatus,
} from '../enums/collection-request-status.enum';
import { CollectionRequestType } from '../enums/collection-request-type.enum';

/**
 * A citizen/institution's recycling pickup request. Committed directly by the
 * producer — there is no cart in the collection flow — with the materials
 * snapped into `collection_request_lines` (name/unit/price/quantity) at
 * creation so later catalogue edits never rewrite history.
 *
 * The unique (sourcePlanId, sourcePlanDate) pair is the once-only guard that
 * lets the plan generator re-run safely: a plan can never produce two requests
 * for the same day. `routeId` + `routeSequence` place the request on the
 * driver's tour (no separate stops table — the request IS the stop).
 */
@Entity('collection_requests')
@Unique(['sourcePlanId', 'sourcePlanDate'])
@Index(['status'])
@Index(['accountId'])
@Index(['routeId'])
@Index(['scheduledAt'])
export class CollectionRequest {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** CR-YYYYMM-##### — generated by the service, never edited. */
  @Column({ name: 'request_number', length: 32, unique: true })
  requestNumber: string;

  @Column({
    type: 'enum',
    enum: CollectionRequestType,
    enumName: 'collection_request_type',
    default: CollectionRequestType.IMMEDIATE,
  })
  type: CollectionRequestType;

  @Column({
    type: 'enum',
    enum: CollectionRequestStatus,
    enumName: 'collection_request_status',
    default: CollectionRequestStatus.CREATED,
  })
  status: CollectionRequestStatus;

  @ManyToOne(() => Account, { nullable: false, onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'account_id' })
  account: Account;

  @Column({ name: 'account_id' })
  accountId: string;

  @Column({ name: 'contact_name', length: 255, nullable: true })
  contactName?: string | null;

  @Column({ name: 'contact_phone', length: 64, nullable: true })
  contactPhone?: string | null;

  /** Free-form address as typed by the producer; the driver reads this. */
  @Column({ name: 'address_text', length: 500, nullable: true })
  addressText?: string | null;

  @Column({ name: 'lat', type: 'decimal', precision: 10, scale: 7, nullable: true })
  lat?: string | null;

  @Column({ name: 'lng', type: 'decimal', precision: 10, scale: 7, nullable: true })
  lng?: string | null;

  /** Future pickup slot (SCHEDULED/ORG_PLAN). Null for IMMEDIATE. */
  @Column({ name: 'scheduled_at', type: 'timestamptz', nullable: true })
  scheduledAt?: Date | null;

  /** Sum of line weights at creation — the dispatch engine's capacity basis. */
  @Column({ name: 'estimated_weight_kg', type: 'decimal', precision: 12, scale: 3, default: 0 })
  estimatedWeightKg: string;

  /** Sum of line totals at creation (unit_price × quantity). */
  @Column({ name: 'estimated_grand_total', type: 'decimal', precision: 14, scale: 2, default: 0 })
  estimatedGrandTotal: string;

  /** Weighed by the driver at PICKING — the payment basis once confirmed. */
  @Column({ name: 'actual_weight_kg', type: 'decimal', precision: 12, scale: 3, nullable: true })
  actualWeightKg?: string | null;

  @Column({ name: 'actual_grand_total', type: 'decimal', precision: 14, scale: 2, nullable: true })
  actualGrandTotal?: string | null;

  /** The driver's tour this request belongs to (null before assignment). */
  @ManyToOne(() => CollectionRoute, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'route_id' })
  route?: CollectionRoute | null;

  @Column({ name: 'route_id', type: 'uuid', nullable: true })
  routeId?: string | null;

  /** Position in the tour; stops are ordered by this, never by creation. */
  @Column({ name: 'route_sequence', type: 'int', nullable: true })
  routeSequence?: number | null;

  /** The plan that generated this request (ORG_PLAN only). */
  @ManyToOne(() => CollectionPlan, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'source_plan_id' })
  sourcePlan?: CollectionPlan | null;

  @Column({ name: 'source_plan_id', type: 'uuid', nullable: true })
  sourcePlanId?: string | null;

  /** The plan's cycle day this request was generated for (YYYY-MM-DD). */
  @Column({ name: 'source_plan_date', type: 'date', nullable: true })
  sourcePlanDate?: string | null;

  @Column({ name: 'cancellation_reason', length: 255, nullable: true })
  cancellationReason?: string | null;

  @Column({ name: 'assigned_at', type: 'timestamptz', nullable: true })
  assignedAt?: Date | null;

  @Column({ name: 'en_route_at', type: 'timestamptz', nullable: true })
  enRouteAt?: Date | null;

  @Column({ name: 'arrived_at', type: 'timestamptz', nullable: true })
  arrivedAt?: Date | null;

  @Column({ name: 'picked_at', type: 'timestamptz', nullable: true })
  pickedAt?: Date | null;

  @Column({ name: 'delivered_at', type: 'timestamptz', nullable: true })
  deliveredAt?: Date | null;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt?: Date | null;

  @Column({ name: 'cancelled_at', type: 'timestamptz', nullable: true })
  cancelledAt?: Date | null;

  @OneToMany(() => CollectionRequestLine, (line) => line.request, {
    cascade: true,
  })
  lines: CollectionRequestLine[];

  @OneToMany(() => CollectionRequestAssignment, (assignment) => assignment.request)
  assignments: CollectionRequestAssignment[];

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
