export enum AccountStatus {
  INACTIVE = 'INACTIVE',
  PENDING_PROFILE = 'PENDING_PROFILE',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  NEED_CHANGES = 'NEED_CHANGES',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED'

}
